kind: Secret
apiVersion: v1
metadata:
  name: bluteksbot
  namespace: bluteks
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: UkVQTEFDRV9NRQ==
  MONGO_URI: UkVQTEFDRV9NRQ==
  OPENAI_API_BEARER_TOKEN: UkVQTEFDRV9NRQ==
  TAVILY_API_KEY: UkVQTEFDRV9NRQ==
